version: '3'

services:

  web:
    build: .
    image: robomission
    command: make server
    volumes:
      - ./backend:/code/backend
      - ./frontend/src:/code/frontend/src
    ports:
      - "8000:8000"