version: '3'

services:

  web:
    build: .
    image: robomission
    command: make server
    volumes:
      - ./backend/domain:/code/backend/domain
      - ./backend/learn:/code/backend/learn
      - ./backend/monitoring:/code/backend/monitoring
      - ./backend/robomission:/code/backend/robomission
      - ./backend/conftest.py:/code/backend/conftest.py
      - ./backend/manage.py:/code/backend/manage.py
      - ./frontend/src:/code/frontend/src
      - ./frontend/.env.development:/code/frontend/.env.development
      - ./frontend/package.json:/code/frontend/package.json
      - ./Makefile:/code/Makefile
    ports:
      - "80:8000"
      - "8000:8000"
    labels:
      traefik.frontend.rule: "Host:robomission.xn--krl-fla.com"
      traefik.docker.network: traefik_default


networks:
  default:
    external:
      name: traefik_default